### ISSUE TITLE
ArgoUML

### ISSUE THREAD

**Issue by ficorax** [stcarrez/atlas#2]
Hi.
Which version of ArgoUML are you using for creating UML models? When I tried to open atlas.zargo my Argo (0.35.1) say:
"XMI external reference error attempting to read : http://argouml.org/user-profiles/AWA.xmi
error message : org.argouml.model.XmiReferenceException: http://argouml.org/user-profiles/AWA.xmi
Please check that the referenced file is available.
If the reference refers to a profile, make sure that the profile is available by doing the following:
(1) Either load a module which contains that profile,
(2) or make sure that the URL can be resolved (...)".
Before I tried same wth 0.34.
In logs I can see that Argo has also problem with Dynamo.xmi interpretation.
thanks
Marek

**Comment by stcarrez** [comment]
Yes, this is version 0.35.1.  Version 0.34 works similar.

Before opening atlas.zargo, you must install the AWA.xmi and Dynamo.xmi UML profiles in ArgoUML.
This is a pain to do it but I've not found any other solution.

These UML profiles are located in the /usr/share/dynamo/base/uml directory after Dynamo and AWA are installed. To configure ArgoUML, go in the Edit -> Settings menu and add the directory in the Default XMI directories list. Beware that you must restart ArgoUML to be able to use the new profiles.

I've posted some info on : https://blog.vacs.fr/vacs/blogs/post.html?post=2014/05/18/Ada-Web-Application--Building-the-UML-model

Then, after restarting ArgoUML, you should be able to load atlas.zargo.

One more serious issue with ArgoUML that I've noticed: it must have an Internet connection when it starts (:-
On startup it downloads some XML or DTD schema definition from the Internet.

This XML download comes from the marvellous XML Java parser library that ArgoUML is using.

**Comment by ficorax** [comment]
I did like your wrote.
After restart ArgoUML in case 0.34 I got something like that:
"org.argouml.model.XmiReferenceRuntimeException: http://argouml.org/user-profiles/Dynamo.xmi
	at org.argouml.model.mdr.XmiReferenceResolverImpl.readExternalDocument(XmiReferenceResolverImpl.java:647)
	at org.netbeans.lib.jmi.xmi.XmiContext.resolve(XmiContext.java:750)
	at org.netbeans.lib.jmi.xmi.XmiContext.resolveExternalReferences(XmiContext.java:839)
	at org.netbeans.lib.jmi.xmi.XmiElement$Content.endElement(XmiElement.java:394)
	at org.netbeans.lib.jmi.xmi.XmiSAXReader.endElement(XmiSAXReader.java:258)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1716)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2881)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:136)
	at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:98)
	at org.netbeans.lib.jmi.xmi.SAXReader.read(SAXReader.java:56)
	at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:267)
	at org.argouml.profile.URLModelLoader.loadModel(URLModelLoader.java:99)
	at org.argouml.profile.FileModelLoader.loadModel(FileModelLoader.java:63)
	at org.argouml.profile.UserDefinedProfile.loadModel(UserDefinedProfile.java:322)
	at org.argouml.profile.UserDefinedProfile.getProfilePackages(UserDefinedProfile.java:745)
	at org.argouml.profile.UserDefinedProfile.getAllCritiquesInModel(UserDefinedProfile.java:664)
	at org.argouml.profile.UserDefinedProfile.getCritics(UserDefinedProfile.java:449)
	at org.argouml.profile.internal.ProfileManagerImpl.registerProfileInternal(ProfileManagerImpl.java:290)
	at org.argouml.profile.internal.ProfileManagerImpl.access$100(ProfileManagerImpl.java:71)
	at org.argouml.profile.internal.ProfileManagerImpl$1.check(ProfileManagerImpl.java:151)
	at org.argouml.profile.internal.ProfileManagerImpl$1.check(ProfileManagerImpl.java:144)
	at org.argouml.profile.internal.DependencyResolver.internalResolve(DependencyResolver.java:114)
	at org.argouml.profile.internal.DependencyResolver.resolve(DependencyResolver.java:83)
	at org.argouml.profile.internal.ProfileManagerImpl.loadProfiles(ProfileManagerImpl.java:413)
	at org.argouml.profile.internal.ProfileManagerImpl.refreshRegisteredProfiles(ProfileManagerImpl.java:408)
	at org.argouml.profile.internal.ProfileManagerImpl.<init>(ProfileManagerImpl.java:138)
	at org.argouml.profile.init.InitProfileSubsystem.init(InitProfileSubsystem.java:64)
	at org.argouml.application.Main.initializeSubsystems(Main.java:425)
	at org.argouml.application.Main.main(Main.java:189)
Caused by: org.argouml.model.XmiException: java.io.FileNotFoundException: http://argouml.tigris.org//user-profiles/Dynamo.xmi
	at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:352)
	at org.argouml.model.mdr.XmiReferenceResolverImpl.readExternalDocument(XmiReferenceResolverImpl.java:644)
	... 37 more
Caused by: java.io.FileNotFoundException: http://argouml.tigris.org//user-profiles/Dynamo.xmi
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:678)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:136)
	at org.netbeans.lib.jmi.xmi.XmiSAXReader.read(XmiSAXReader.java:98)
	at org.netbeans.lib.jmi.xmi.SAXReader.read(SAXReader.java:56)
	at org.argouml.model.mdr.XmiReaderImpl.parse(XmiReaderImpl.java:267)
	... 38 more
[org.netbeans.lib.jmi.Logger] XMI parsing error at line: 17027: http://argouml.org/user-profiles/Dynamo.xmi"

And then I can not open atlas.zargo file from your Atlas github repository. 
Files which I create myself I can open without problem. Of course still is this long error message...

**Comment by stcarrez** [comment]
Hi!

I've made this video some time ago to explain how to do the setup.

https://www.youtube.com/watch?v=M25eAm3Mly8

I think what is tricky is that once you add the directory, you have to stop Argouml and start it again.

Then, you go again in the Settings -> Profile configuration and you have to choose the Dynamo and AWA profiles.  I often forget this last step.  After choosing the Dynamo + AWA profiles (see Video), you have to stop Argouml again.

This setting is a real pain but once it's done, you're all set.

**Comment by ficorax** [comment]
Ok. I'll try. Thanks a lot.

**Comment by ficorax** [comment]
Attempt to setup default profile directory not succeed. Still during start complaining about Dynamo.xmi. But I just add direct files AWA.xmi and Dynamo.xmi and everything was ok.
Anyway, thanks for replies
